name: Bug report -- 问题反馈
description: Create a report to help us improve
title: "[BUG] Briefly describe the problem you are facing in one sentence."
labels: ["bug"]
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: "
在提交之前，请确认
Please verify that you've followed these steps
"
      options:
        - label: "
The version I'm running is up to date.
已安装最新版本.
"
          required: true
        - label: "
I have tried right click and menu have shown
单击鼠标右键正常显示菜单
"
          required: true
        - label: "
I can see the splash or loading screen.
可以正常看到屏幕中有显示加载或首页的内容
"
          required: true
        - label: "
I have searched on the [issue tracker](……/) for a related issue.
我已经在 [Issue Tracker](……/) 中找过我要提出的问题
"
          required: true
  - type: input
    attributes:
      label: |
        BingGPT Version
        软件版本
      description: |
        If not the current version, please update first
        如果非最新版请先更新
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: |
        What OS are you seeing the problem on?
        操作系统/桌面环境
      multiple: true
      options:
        - macOS
        - Windows
        - Linux (GTK-based Desktop)
        - Linux (QT-based Desktop)
        - Linux (Others)
    validations:
      required: true
  - type: dropdown
    id: arch
    attributes:
      label: |
        What Architecture are you seeing the problem on?
        系统指令集
      multiple: true
      options:
        - x86
        - arm64
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        A clear and concise description of what the bug is.
        简要描述您遇到的问题
      placeholder: |
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
        Tip: 拖入即可插入文件
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error Logs
      description: |
        Paste the error log or ScreenShoot that contains the error (if exists)
        请粘贴或截图遇到的错误。
      placeholder: |
        How to get the error (if you can't see the error dialog)?
        1. right click, then select "Open Devtools" in the menu
        2. in devtools, head to Console and the error id here.
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
        Tip: 拖入即可插入文件
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
