blank_issues_enabled: false
contact_links:
  - name: BingGPT Community Support
    url: https://github.com/fangkehou-team/BingGPT/discussions
    about: Please ask and answer questions about BingGPT here.
