name: Build/release

on:
  push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
                    
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: npm install
        run: |
          pnpm install

      # step4: build app or release if new tag have made.
      - name: build app and release
        run: |
          pnpm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cleanup artifacts for windows
        if: matrix.os == 'windows-latest'
        run: |
          pnpm dlx rimraf release/* --glob "!(*.exe)"

      - name: cleanup artifacts for macos
        if: matrix.os == 'macos-latest'
        run: |
          pnpm dlx rimraf "release/!(*.dmg)"

      - name: cleanup artifacts for macos
        if: matrix.os == 'ubuntu-latest'
        run: |
          pnpm dlx rimraf "release/!(*.deb|*.AppImage|*.rpm)"

      # step6: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: 'release/'
